version: 2
updates:
  # pubspec.yaml dependencies
  - package-ecosystem: "pub"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5

  # The workflow files in .github/workflows themselves
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
