// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCeVGLQMIMhq7pNpBfh653jeoXvhmzcqE4',
    appId: '1:1043925918030:web:6fc492bdd8eebbee267e1f',
    messagingSenderId: '1043925918030',
    projectId: 'travelstories-app',
    authDomain: 'travelstories-app.firebaseapp.com',
    storageBucket: 'travelstories-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBqkjU-vnoZxnUg3Cl6dO-t18RgFzFXi4U',
    appId: '1:1043925918030:android:b2ad262758574271267e1f',
    messagingSenderId: '1043925918030',
    projectId: 'travelstories-app',
    storageBucket: 'travelstories-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBIDGDckwEoPjOqi08ApYaDB0Dh1Hj4-s4',
    appId: '1:1043925918030:ios:ba7032740d0643e8267e1f',
    messagingSenderId: '1043925918030',
    projectId: 'travelstories-app',
    storageBucket: 'travelstories-app.firebasestorage.app',
    iosBundleId: 'com.travelstories.app',
  );
}
